DROP DATABASE IF EXISTS employee_tracker;
Create DATABASE employee_tracker;
Use employee_tracker;

CREATE TABLE DEPARTMENTS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
 );



CREATE TABLE ROLES(
    ID NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(40) NOT NULL,
    SALARY DECIMAL(10,2),
    DEPARTMENT_ID INT REFERENCES DEPARTMENT(ID)
);

CREATE TABLE EMPLOYEE(
    ID NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(40) NOT NULL,
    LASTNAME VARCHAR(40) NOT NULL,
    ROLE_ID INT REFERENCES ROLES(ID),
    MANAGER_ID INT REFERENCES EMPLOYEE(ID)

);

